---
#-------------------------------
# General Site Settings

title:
logo:
author: themefisher
description: this is meta description
email: nasaenakate@gmail.com
phone: +1 607 280 4691
address: Stamford, Connecticut USA
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Patents, link: "/patents" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Sae Na, <br> Robotics Engineer

social:
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/saenana/" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: Explore my work below!

blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# My Team Section
team:
  - title: "Jack Schenziwe"
    image: "assets/images/team/member-1.png"
    designation: "Project Manager"

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: Web Design, color: "#fdb157", value: "90%" }
  - { name: Logo Design, color: "#9473e6", value: "60%" }

#-------------------------------
# Experience Section

experience-title: Experience
experience:
  - {
      name: Mechatronics Designer,
      icon: "icon-asml.png",
      date: "Jan 2020 - Present",
      organization: "ASML",
    }
  - {
      name: Hydraulics & Landing Gear Engineering Intern,
      icon: "icon-honda.png",
      date: "May 2018 - Aug 2018",
      organization: "Honda Aircraft Company",
    }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Master of Science in Robotics and Controls (Mechanical Engineering),
      icon: "columbia-logo.png",
      date: "2025",
      organization: "Columbia University",
    }
  - {
      name: Bachelor of Science in Mechanical Engineering,
      icon: "cornell-logo.png",
      date: "2019",
      organization: "Cornell University",
    }

#-------------------------------
# Services Section

services-title: Services
services:
  - {
      name: UI Design,
      icon: ti-palette,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      active: ,# Add true to select section
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/catbot.png"
    url: "https://youtu.be/nrEPlOXd7_k"

  - image: "assets/images/portfolio/rr.png"
    url: "https://cev.engineering.cornell.edu/#/competition"

  - image: "assets/images/portfolio/outreach.png"
    url: "https://www.ctinsider.com/news/thehour/article/Norwalk-robotics-team-gets-inside-look-of-15084347.php"

  - image: "assets/images/portfolio/gen-design.png"
    url: "/assets/images/portfolio/gen-design-report.pdf"

  - image: "assets/images/portfolio/robotlearning-img.png"
    url: "#"
    
  - image: "assets/images/portfolio/comp-stops.png"


  - image: "assets/images/portfolio/carbon-fiber.png"
    url: "#"

  - image: "assets/images/portfolio/amr.png"
    url: "/assets/images/portfolio/amr-report.pdf"

  - image: "assets/images/portfolio/mechatronics.png"
    url: "#"

  - image: "assets/images/portfolio/motor-dyno.png"
    url: "#"

  - image: "assets/images/portfolio/rr-steering-proto.png"
    url: "#"

  - image: "assets/images/portfolio/veggie-chopper2.png"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "Robotics", type: "robotics" }
  - { title: "ML", type: "learning" }
  - { title: "Design", type: "design" }
  - { title: "Materials", type: "materials" }
  - { title: "News", type: "news" }

portfolio-items:
  - image: "assets/images/portfolio/catbot.png"
    url: "https://youtu.be/nrEPlOXd7_k"
    portfolio-type:
      - type: "robotics"

  - image: "assets/images/portfolio/rr.png"
    url: "https://cev.engineering.cornell.edu/#/competition"
    portfolio-type:
      - type: "design"
      - type: "materials"

  - image: "assets/images/portfolio/outreach.png"
    url: "https://www.ctinsider.com/news/thehour/article/Norwalk-robotics-team-gets-inside-look-of-15084347.php"
    portfolio-type:
      - type: "news"

  - image: "assets/images/portfolio/gen-design.png"
    url: "/assets/images/portfolio/gen-design-report.pdf"
    portfolio-type:
      - type: "design"
      - type: "materials"

  - image: "assets/images/portfolio/robotlearning-img.png"
    url: "#"
    portfolio-type:
      - type: "learning"

  - image: "assets/images/portfolio/comp-stops.png"
    portfolio-type:
      - type: "design"
      - type: "materials"

  - image: "assets/images/portfolio/carbon-fiber.png"
    url: "#"
    portfolio-type:
      - type: "materials"

  - image: "assets/images/portfolio/amr.png"
    url: "/assets/images/portfolio/amr-report.pdf"
    portfolio-type:
      - type: "robotics"

  - image: "assets/images/portfolio/mechatronics.png"
    url: "#"
    portfolio-type:
      - type: "robotics"
      - type: "design"

  - image: "assets/images/portfolio/motor-dyno.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image: "assets/images/portfolio/rr-steering-proto.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image: "assets/images/portfolio/veggie-chopper2.png"
    url: "#"
    portfolio-type:
      - type: "design"

#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: nasaenakate@gmail.com